const videos = [
  {
    id: 1,
    picture: "./assets/video.jpg",
    title: "Test",
    editor: "Test",
    views: "10K",
    time: "test",
  },
  {
    id: 2,
    picture: "./assets/video.jpg",
    title: "Test",
    editor: "Test",
    views: "10K",
    time: "test",
  },
  {
    id: 3,
    picture: "./assets/video.jpg",
    title: "Test",
    editor: "Test",
    views: "10K",
    time: "test",
  },
  {
    id: 4,
    picture: "./assets/video.jpg",
    title: "Test",
    editor: "Test",
    views: "10K",
    time: "test",
  },
  {
    id: 5,
    picture: "./assets/video.jpg",
    title: "Test",
    editor: "Test",
    views: "10K",
    time: "test",
  },
  {
    id: 6,
    picture: "./assets/video.jpg",
    title: "Test",
    editor: "Test",
    views: "10K",
    time: "test",
  },
  {
    id: 7,
    picture: "./assets/video.jpg",
    title: "Test",
    editor: "Test",
    views: "10K",
    time: "test",
  },
  {
    id: 8,
    picture: "./assets/video.jpg",
    title: "Test",
    editor: "Test",
    views: "10K",
    time: "test",
  },
  {
    id: 9,
    picture: "./assets/video.jpg",
    title: "Test",
    editor: "Test",
    views: "10K",
    time: "test",
  },
  {
    id: 10,
    picture: "./assets/video.jpg",
    title: "Test",
    editor: "Test",
    views: "10K",
    time: "test",
  },
  {
    id: 11,
    picture: "./assets/video.jpg",
    title: "Test",
    editor: "Test",
    views: "10K",
    time: "test",
  },
  {
    id: 12,
    picture: "./assets/video.jpg",
    title: "Test",
    editor: "Test",
    views: "10K",
    time: "test",
  },
  {
    id: 13,
    picture: "./assets/video.jpg",
    title: "Test",
    editor: "Test",
    views: "10K",
    time: "test",
  },
  {
    id: 14,
    picture: "./assets/video.jpg",
    title: "Test",
    editor: "Test",
    views: "10K",
    time: "test",
  },
  {
    id: 15,
    picture: "./assets/video.jpg",
    title: "Test",
    editor: "Test",
    views: "10K",
    time: "test",
  },
];

const myDiv = document.querySelector(".videos-container");

videos.map((element) => {
  myDiv.innerHTML += `<img class="each-video-card" src="${element.picture}" alt="${element.id}"/>`;
});
